### ISSUE TITLE
Leap year intervals

### ISSUE THREAD

**Issue by lxbarth** [kkaefer/chrono.js#3]
The second assertion here fails:

```
assert.eql(new Date('Feb 28 2004').interval(new Date('Feb 28 2005')), ['1 year']);
assert.eql(new Date('Feb 28 2004').interval(new Date('Mar 1 2005')), ['1 year', '1 day']);
```

Not sure how you'd like to go about this:
- The first result of interval() is actually not correct if you take a year to be 365 days. There are 366 days between Feb 28 04 and Feb 28 05.
- The second result of interval() is actually correct (it yields 1 year, 2 days) which is what I'd expect but the test looks for one day less.

**Comment by kkaefer** [comment]
I intentionally wrote this so that a year doesn't equal to 365 days (just like a month isn't a fixed amount of days). I did this to avoid getting an interval of "9 years, 3 days" between August 1 2003 and August 1 2012, which feels unintuitive.

This is doesn't always work though, e.g. what's the interval between "Feb 28 2003" and "Mar 1 2004"?

**Comment by lxbarth** [comment]
What about delegating this decision to the API user?

`function interval(from, to, countLeapDays = false)`

**Comment by kkaefer** [comment]
@lxbarth: What is the use case for this? I'm a bit hesitant to complicate the API unless there's a good reason to.

**Comment by lxbarth** [comment]
Got nothing, just throwing out an option.
